#测试环境配置
server:
  #端口
  port: 8088
spring:
  profiles: test
  #redis配置
#  redis:
#      database: 3
#      host: test.qianchubao.cn
#      port: 6379
#      password: yuanchengredis      # 密码（默认为空）
#      timeout: 6000  # 连接超时时长（毫秒）
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
        validationQuery: SELECT 1
        initialSize: 10
        minIdle: 10
        maxActive: 200
        minEvictableIdleTimeMillis: 180000
        testOnBorrow: false
        testWhileIdle: true
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        logAbandoned: true
        poolPreparedStatements: true
        maxOpenPreparedStatements: 100
    sys:
        url: jdbc:mysql://192.168.1.172:3306/mybatis?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: yuanchengmysql
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 5
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    manage:
        url: jdbc:mysql://192.168.1.172:3306/mybatie_2?useUnicode=true&amp;characterEncoding=utf8
        username: root
        password: yuanchengmysql
          # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 5
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

#日志
#logging:
#  config: classpath:log/logback.xml
#  path: /home/log/mysiteforme
#  level: debug

#自定义配置属性
#源码生成文件夹
#本地路径
source-code-dic: home/mysiteforme/mysite
source-code-zipfile: home/mysiteforme/源码.rar

#搜索文件生成包的位置
#本地路径
lucence-dic: home/mysiteforme/lucence